default_language_version:
    python: python3.13
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.10
      hooks:
          - id: ruff
            name: Ruff
            description: Run Ruff linter and autofixer
            args:
                - --fix
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.15.0
      hooks:
          - id: mypy
            name: MyPy
            description: Run static type checking
            args:
                - --config-file
                - pyproject.toml
            additional_dependencies:
                - beautifulsoup4>=4.10.0
                - homeassistant-stubs==2025.5.2
                - pyalarmdotcomajax>=0.6.0-beta.7
                - types-beautifulsoup4
                - types-requests
                - mypy_extensions
                - typing_extensions
                - types-PyYAML
    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.6
      hooks:
          - id: codespell
            additional_dependencies:
                - tomli
            args:
                - --toml
                - pyproject.toml
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.32.0
      hooks:
          - id: yamllint
            args:
                - -d
                - relaxed
            exclude: (\.vscode|\.devcontainer|\.github)
    - repo: https://github.com/ComPWA/taplo-pre-commit
      rev: v0.9.3
      hooks:
          - id: taplo-format
          - id: taplo-lint
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-json
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
