[tool.codespell]
skip = "./.*,*.csv,*.json,*.html,*.aspx,tests/test_device_extensions.py,pyalarmdotcomajax/models/jsonapi/*"
count = ""
quiet-level = 2
ignore-words-list = "hass,alot,datas,dof,dur,farenheit,hist,iff,ines,ist,lightsensor,mut,nd,pres,referer,ser,serie,te,technik,ue,uint,visability,wan,wanna,withing,windo"

[tool.mypy]
exclude = [
    "tests/",
    "build/",
    ".ruff_cache/",
    ".mypy_cache/",
    "references/",
    ".pytest_cache",
    "old",
]
python_version = "3.13"
show_error_codes = true
ignore_missing_imports = true
strict_equality = true
warn_incomplete_stub = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_subclassing_any = false
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
warn_unreachable = true
pretty = true
show_absolute_path = true
show_error_context = true
disallow_untyped_calls = false
# explicit_package_bases = true

[tool.ruff]
target-version = "py313"
line-length = 115
respect-gitignore = true
lint.ignore = [
    "D202",
    "D203",
    "D404",
    "D212",
    "D406",
    "D407",
    "E731",
    "TRY003",
    "TRY301",
    "PLR2004",
    "PLR0913",
    "PLR0912",
    "PLR0915",
    "PLR0911",
    "S301",
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
    "E501",
    "TRY400",
    "D107",
    "TD002",
    "TD003",
    "TC003",
    "TC002",
    "T201",
    "TID252",
]
lint.unfixable = ["F841"]
lint.select = [
    "A",
    "ASYNC",
    "B",
    "C",
    "D",
    "E",
    "F",
    "I",
    "G",
    "PL",
    "RUF",
    "FA",
    "FBT",
    "TID",
    "SLF",
    "SIM",
    "ICN001",
    "PGH004",
    "PLC0414",
    "RET",
    "S",
    "LOG",
    "PERF",
    "PIE",
    "ICN",
    "TC",
    "TD",
    "T20",
    "PT",
    "Q",
    "YTT",
    "TRY",
    "UP",
    "W",
]
lint.extend-safe-fixes = ["UP006"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id", "type"]

[tool.ruff.lint.flake8-type-checking]
quote-annotations = true

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.lint.mccabe]
max-complexity = 25

[tool.tomlsort]
in_place = true
spaces_before_inline_comment = 4
spaces_indent_inline_array = 4
trailing_comma_inline_array = false
